# Micromamba environment file
# https://marketplace.visualstudio.com/items?itemName=corker.vscode-micromamba

name: ParallelSimulatedAnnealing

channels:
  - conda-forge

dependencies:
  - python
  - ipykernel
  - tqdm
  - matplotlib
  - numpy
  - pandas
  - py-cpuinfo
  - yapf