# Micromamba environment file
# https://marketplace.visualstudio.com/items?itemName=corker.vscode-micromamba

name: ParallelSimulatedAnnealing

channels:
  - conda-forge

dependencies:
  - python=3.11
  - jupyterlab=4.0
  - tqdm=4.65
  - matplotlib=3.7
  - numpy=1.25
  - pandas=2.0
  - py-cpuinfo=9.0
  - yapf=0.33